version: "3.7"

services:
  app:
    build: .
    working_dir: /app
    environment:
      MIX_ENV: test
    volumes:
      - build_cache:/app/_build
      - deps_cache:/app/deps

volumes:
  deps_cache: {}
  build_cache: {}